apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grades-control-api
  template:
    metadata:
      labels:
        app: grades-control-api
    spec:
      containers:
        - name: grades-control-api
          image: carlosgeorge248/grades-control-api:v2
          ports:
            - containerPort: 3001
          env:
            - name: APP_URL
              value: http://localhost:3000
